# Generated by Django 4.2.16 on 2024-12-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=100)),
                ('issue_description', models.CharField(max_length=500)),
                ('issue_status', models.BooleanField()),
                ('date_created', models.DateField()),
            ],
        ),
    ]
