# Generated by Django 4.2.16 on 2024-12-02 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTrackerBackendApp', '0005_alter_issue_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 2, 19, 0, 4, 952558, tzinfo=datetime.timezone.utc)),
        ),
    ]
