# Generated by Django 4.2.16 on 2024-12-05 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTrackerBackendApp', '0006_alter_issue_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 20, 52, 40, 749552, tzinfo=datetime.timezone.utc)),
        ),
    ]
