# Generated by Django 4.2.16 on 2024-12-22 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTrackerBackendApp', '0007_alter_issue_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 20, 24, 37, 838055, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(default='Open'),
        ),
    ]
