# Generated by Django 4.2.16 on 2024-12-22 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTrackerBackendApp', '0008_alter_issue_date_created_alter_issue_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 20, 46, 21, 673838, tzinfo=datetime.timezone.utc)),
        ),
    ]
