# Generated by Django 4.2.16 on 2024-12-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issueTrackerBackendApp', '0009_alter_issue_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
